server:
  port: 8067

# CONEXION A BASE DE DATOS
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gotest
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driverx
# Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
