server:
  port: 8024
spring:
  datasource:
    url: jdbc:postgresql://10.35.3.64:5433/facturacion_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jdbc:
        lob:
         non_contextual_creational: true

