server:
  port: 8080
spring:
  application:
    name: es-sucursal
  datasource:
    url: ${SERVER_POSTGRES} 
    username: ${USER_SERVER_POSTGRES}
    password: ${PASS_SERVER_POSTGRES}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate: 
      generate_statistics: true
      jdbc:
        order_updates: true
        order_inserts: true
        batch_size: 1000
        lob:
         non_contextual_creational: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
