server:
  port: 8001
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
# ESPECIFICACIONES DE KAFKA
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup

# TOPICO DE MENSAJERIA
topic:
   name: "TopicbitacoraSolicitud" 
