server:
  port: 5555
spring:
  application:
    name: ms-notificarcomprobanteprocesado 
  datasource:
    url: jdbc:postgresql://10.35.2.46:3100/BillingAppDB
    username: postgres
    password: M#3!0{AZ2:Mw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate: 
      generate_statistics: true
      jdbc:
        order_updates: true
        order_inserts: true
        batch_size: 1000
        lob:
         non_contextual_creational: true
logging:
  file: ms-notificarcomprobanteprocesado.log  # Nombre del archivo
  path: .   # Directorio de logs (punto indica la carpeta actual, es decir, la raíz del proyecto)
  file-name-format: ${logging.path}/${logging.file:-ms-notificarcomprobanteprocesado}.%d{yyyy-MM-dd}.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
