server:
  port: 8083

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    password: dghbyfhmtvdgqsug
    port: 587
    properties:
       mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    username: gotalentpruebas@gmail.com

